name: Backend Pre-commit

on:
  pull_request:
    branches:
      - "16.0*"
    paths:
      - "whatsapp_cloud_api_backend/**"
      - ".pre-commit-config.yaml"
      - ".pylintrc*"
      - ".ruff.toml"
      - ".github/workflows/backend-pre-commit.yml"
  push:
    branches:
      - "16.0"
      - "16.0*"
    paths:
      - "whatsapp_cloud_api_backend/**"
      - ".pre-commit-config.yaml"
      - ".pylintrc*"
      - ".ruff.toml"
      - ".github/workflows/backend-pre-commit.yml"

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Get python version
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install pre-commit
        run: pip install pre-commit==4.5.1
      - name: Backend pre-commit checks
        run: |
          # Get all files except frontend directory
          git ls-files | grep -v '^frontend/' | xargs --no-run-if-empty pre-commit run --show-diff-on-failure --color=always --files || exit 1
        env:
          # Skip frontend hooks in backend workflow
          # DOCS https://pre-commit.com/#temporarily-disabling-hooks
          SKIP: oca-gen-addon-readme,frontend-prettier,frontend-eslint,frontend-typescript
      - name: Check that all files generated by pre-commit are in git
        run: |
          newfiles="$(git ls-files --others --exclude-from=.gitignore)"
          if [ "$newfiles" != "" ] ; then
              echo "Please check-in the following files:"
              echo "$newfiles"
              exit 1
          fi
